#Run a static analysis
name: Static Analysis
on:
    pull_request: {}
    push:
        branches: [develop, master]
    repository_dispatch:
        types: [element-web-notify]
env:
    # These must be set for fetchdep.sh to get the right branch
    REPOSITORY: ${{ github.repository }}
    PR_NUMBER: ${{ github.event.pull_request.number }}
jobs:
    # Removing until we fix the crash :
    # Error: matrix-react-sdk/src/autocomplete/CommandProvider.tsx(38,24): error TS2589:
    # Type instantiation is excessively deep and possibly infinite.
    #ts_lint:
        #name: "Typescript Syntax Check"
        #runs-on: ubuntu-latest
        #steps:
        #    - uses: actions/checkout@v4

    #         - uses: actions/setup-node@v3
    #           with:
    #               cache: "yarn"

    #         - name: Install Dependencies
    #           run: "./scripts/layered.sh"

    #         - name: Typecheck
    #           run: "yarn run lint:types"

    # tchap : tchap does not use extensively i18n
    # i18n_lint:
    #    name: "i18n Check"
    #    uses: matrix-org/matrix-web-i18n/.github/workflows/i18n_check.yml@main

    js_lint:
        name: "ESLint"
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Get Node Version
              id: node_version
              run: echo ::set-output name=node_version::$(node -e 'console.log(require("./package.json").engines.node)')
            - uses: actions/setup-node@v3
              with:
                  cache: "yarn"
                  node-version: ${{ steps.node_version.outputs.node_version }}

            # Does not need branch matching as only analyses this layer
            - name: Install Deps
              run: "yarn install --frozen-lockfile"

            - name: Run Linter
              run: "yarn run lint:js"

    style_lint:
        name: "Style Lint"
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Get Node Version
              id: node_version
              run: echo ::set-output name=node_version::$(node -e 'console.log(require("./package.json").engines.node)')
            - uses: actions/setup-node@v3
              with:
                  cache: "yarn"
                  node-version: ${{ steps.node_version.outputs.node_version }}

            # Needs branch matching as it inherits .stylelintrc.js from matrix-react-sdk
            - name: Install Dependencies
              run: "yarn install --pure-lockfile"

            - name: Run Linter
              run: "yarn run lint:style"

    # tchap : do we need this ? Does it pass ?
    analyse_dead_code:
        name: "Analyse Dead Code"
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - uses: actions/setup-node@v3
              with:
                  cache: "yarn"

            - name: Install Deps
              run: "scripts/layered.sh"

            - name: Dead Code Analysis
              run: "yarn run analyse:unused-exports"
